# Generated by Django 2.1.4 on 2018-12-26 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.CharField(default=uuid.UUID('d732832b-2e4c-4b24-94df-585dd0aa8ed9'), max_length=40)),
            ],
        ),
    ]
